name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: stylua
      - uses: fish-actions/install-fish@v1
      - uses: pre-commit/action@v2.0.3
